In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre - insurance_pre.csv")
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [3]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (independent, dependent, test_size=0.30, random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [6]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)


In [7]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(criterion='squared_error',max_features='sqrt')
regressor.fit(x_train, y_train)

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


,n_estimators,100
,criterion,'squared_error'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [8]:
y_pred=regressor.predict(x_test)

In [9]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8679900477128711

In [10]:
import pickle
filename='preprocessinginputoutput.sav'

In [11]:
pickle.dump(regressor, open(filename, 'wb'))

In [12]:
preinput=sc.transform([[100, 800, 0, 1, 0]])
preinput

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[  4.32192006, 123.43005305,  -0.89833872,   1.02378711,
         -0.50466988]])

In [13]:
loaded_model=pickle.load(open('preprocessing.sav', 'rb'))
result=loaded_model.predict(preinput)
result

array([12764.425712])

In [14]:
preoutput=scy.inverse_transform([result])
preoutput

array([[1.51574991e+08]])

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 11
BMI: 22
Children: 5
Sex Male 0 or 1: male


ValueError: invalid literal for int() with base 10: 'male'